project_id = "ogkpokpxycvxwsrdrddj"

[functions.analyze-outfit]
verify_jwt = false

[functions.chat-styloren]
verify_jwt = false

[functions.compare-outfits]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.log-app-open]
verify_jwt = false

[functions.on-auth-event]
verify_jwt = false

[functions.log-session-start]
verify_jwt = false

[functions.log-hourly-active-users]
verify_jwt = false
