import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Sparkles, ArrowLeft, X, Loader2, Eye, EyeOff } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Alert, AlertDescription } from "@/components/ui/alert";

const TermsContent = () => (
  <div className="text-xs text-foreground space-y-3">
    <p className="text-muted-foreground text-xs">Last updated: December 18, 2025</p>
    
    <p>
      Welcome to Styloren. By accessing or using the Styloren mobile application ("App"), you agree to comply with and be bound by these Terms & Conditions ("Terms"). If you do not agree, please do not use the App.
    </p>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">1. Use of the App</h2>
    <p className="mb-2">
      Styloren provides AI-powered outfit analysis and styling recommendations for informational and personal use only.
    </p>
    <p className="mb-1">You agree to:</p>
    <ul className="list-disc pl-4 space-y-0.5 mb-3">
      <li>Use the App lawfully and responsibly</li>
      <li>Not misuse, reverse engineer, or attempt to disrupt the App or its services</li>
      <li>Not upload unlawful, harmful, or offensive content</li>
    </ul>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">2. AI-Generated Recommendations</h2>
    <ul className="list-disc pl-4 space-y-0.5 mb-3">
      <li>Styling suggestions are generated by artificial intelligence.</li>
      <li>Recommendations are advisory only and subjective in nature.</li>
      <li>Styloren does not guarantee fashion outcomes, personal satisfaction, or results.</li>
    </ul>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">3. User Content & Scan History</h2>
    <ul className="list-disc pl-4 space-y-0.5 mb-3">
      <li>When you upload outfit photos, Styloren processes them to generate styling recommendations.</li>
      <li>By default, your scans and analysis may be saved to your Scan History for your convenience.</li>
      <li>You may disable scan history storage at any time via Account → My Activity → Scan History.</li>
      <li>You retain ownership of your content. Styloren does not claim ownership over your photos.</li>
    </ul>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">4. Accounts & Security</h2>
    <ul className="list-disc pl-4 space-y-0.5 mb-3">
      <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
      <li>You agree to notify us immediately of any unauthorized access to your account.</li>
      <li>Styloren is not responsible for losses caused by unauthorized access due to user negligence.</li>
    </ul>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">5. Subscriptions & Payments</h2>
    <ul className="list-disc pl-4 space-y-0.5 mb-3">
      <li>Styloren may offer paid plans and features.</li>
      <li>Prices, features, and availability may change at any time.</li>
      <li>All payments are handled via third-party payment platforms and are subject to their terms.</li>
      <li>Refunds, if applicable, follow platform-specific policies.</li>
    </ul>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">6. Intellectual Property</h2>
    <ul className="list-disc pl-4 space-y-0.5 mb-3">
      <li>All app content, branding, design, and software are the property of Styloren.</li>
      <li>You may not copy, reproduce, or redistribute any part of the App without permission.</li>
    </ul>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">7. Limitation of Liability</h2>
    <p className="mb-1">Styloren shall not be liable for:</p>
    <ul className="list-disc pl-4 space-y-0.5 mb-2">
      <li>Any indirect or consequential damages</li>
      <li>Loss of data, satisfaction, or personal decisions made based on AI suggestions</li>
      <li>Service interruptions or technical issues beyond reasonable control</li>
    </ul>
    <p className="mb-3">Use of the App is at your own discretion and risk.</p>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">8. Termination</h2>
    <p className="mb-3">
      Styloren reserves the right to suspend or terminate access to the App if these Terms are violated.
    </p>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">9. Changes to These Terms</h2>
    <p className="mb-3">
      We may update these Terms from time to time. Continued use of the App after changes means you accept the updated Terms.
    </p>

    <h2 className="font-display text-sm font-semibold text-foreground mt-4 mb-2">10. Contact Us</h2>
    <p className="mb-1">
      For questions or concerns regarding these Terms, contact:
    </p>
    <p>
      📧 <a href="mailto:help@styloren.com" className="text-primary underline">help@styloren.com</a>
    </p>
  </div>
);

const PrivacyContent = () => (
  <div className="space-y-3 text-xs text-foreground font-body">
    <p className="text-muted-foreground text-xs">Last updated: December 18, 2025</p>
    
    <p>
      Styloren ("we", "our", or "us") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, store, and protect your data when you use the Styloren mobile application.
    </p>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">1. Information We Collect</h2>
      <p className="mb-2">When you use Styloren, we may collect the following information:</p>
      
      <h3 className="font-semibold mb-1">a) Information You Provide</h3>
      <ul className="list-disc list-inside space-y-0.5 mb-2 text-muted-foreground">
        <li>Email address or login information</li>
        <li>Outfit photos you upload for analysis</li>
        <li>Messages and prompts you enter in the chat feature</li>
      </ul>

      <h3 className="font-semibold mb-1">b) Automatically Collected Information</h3>
      <ul className="list-disc list-inside space-y-0.5 mb-2 text-muted-foreground">
        <li>App usage data (such as feature usage and timestamps)</li>
        <li>Device information (basic, non-identifying technical data)</li>
      </ul>

      <p className="text-muted-foreground">
        We do not collect sensitive personal information such as government IDs, financial details, or precise location data.
      </p>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">2. How We Use Your Information</h2>
      <p className="mb-1">We use your information to:</p>
      <ul className="list-disc list-inside space-y-0.5 text-muted-foreground">
        <li>Analyze outfits and provide AI-powered styling suggestions</li>
        <li>Show your previous scans and analysis within the app</li>
        <li>Improve app features and user experience</li>
        <li>Respond to support requests and feedback</li>
        <li>Maintain app security and prevent misuse</li>
      </ul>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">3. Photo & Scan Data</h2>
      <ul className="list-disc list-inside space-y-0.5 text-muted-foreground">
        <li>Outfit images are uploaded only to generate styling recommendations.</li>
        <li>Scan results and images may be stored so you can view your scan history.</li>
        <li>Your photos are not shared publicly and are not visible to other users.</li>
      </ul>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">4. Data Sharing</h2>
      <p className="mb-2">We do not sell, rent, or trade your personal data.</p>
      <p className="mb-1">We may share limited data only when necessary:</p>
      <ul className="list-disc list-inside space-y-0.5 text-muted-foreground">
        <li>With trusted service providers strictly to operate the app</li>
        <li>If required by law or legal process</li>
      </ul>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">5. Data Security</h2>
      <p className="mb-1">We take reasonable steps to protect your data, including:</p>
      <ul className="list-disc list-inside space-y-0.5 text-muted-foreground">
        <li>Secure connections (HTTPS)</li>
        <li>Access control to user data</li>
        <li>Private storage for uploaded images</li>
      </ul>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">6. Your Choices & Control</h2>
      <p className="mb-1">You can:</p>
      <ul className="list-disc list-inside space-y-0.5 text-muted-foreground">
        <li>View your scan history inside the app</li>
        <li>Manually delete scans from your history</li>
        <li>Contact us if you have questions about your data</li>
      </ul>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">7. Children's Privacy</h2>
      <p className="text-muted-foreground">
        Styloren is not intended for children under the age of 13. We do not knowingly collect personal data from children.
      </p>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">8. Changes to This Policy</h2>
      <p className="text-muted-foreground">
        We may update this Privacy Policy from time to time. Any changes will be reflected on this page with an updated date.
      </p>
    </section>

    <section>
      <h2 className="font-display text-sm font-semibold mb-2">9. Contact Us</h2>
      <p className="text-muted-foreground">
        If you have questions, feedback, or concerns about this Privacy Policy or your data, please contact us:
      </p>
      <p className="mt-1">
        📧 <a href="mailto:help@styloren.com" className="text-primary underline">help@styloren.com</a>
      </p>
    </section>
  </div>
);

const Auth = () => {
  const { user, isLoading, termsAccepted, refetchTerms } = useAuth();
  const [isLogin, setIsLogin] = useState(true);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [termsChecked, setTermsChecked] = useState(false);
  const [showTermsDialog, setShowTermsDialog] = useState(false);
  const [showPrivacyDialog, setShowPrivacyDialog] = useState(false);
  
  
  // Forgot password states
  const [showForgotPassword, setShowForgotPassword] = useState(false);
  const [forgotPasswordStep, setForgotPasswordStep] = useState<"email" | "otp" | "newPassword">("email");
  const [otp, setOtp] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [resetSuccessMessage, setResetSuccessMessage] = useState<string | null>(null);
  const [verificationToken, setVerificationToken] = useState<string | null>(null);
  const [keepSignedIn, setKeepSignedIn] = useState(true);
  
  const navigate = useNavigate();
  const { toast } = useToast();

  // Redirect logged-in users (terms are accepted during signup, so skip the gate)
  useEffect(() => {
    const autoAcceptAndRedirect = async () => {
      if (!isLoading && user) {
        // If terms not yet accepted, auto-accept them (since signup already requires acceptance)
        if (termsAccepted === false) {
          await supabase
            .from("user_subscriptions")
            .upsert({
              user_id: user.id,
              terms_accepted: true,
              terms_accepted_timestamp: new Date().toISOString(),
            }, { onConflict: 'user_id' });
          await refetchTerms();
        }
        // Redirect to analyze once terms are handled
        if (termsAccepted === true || termsAccepted === false) {
          navigate("/analyze", { replace: true });
        }
      }
    };
    autoAcceptAndRedirect();
  }, [isLoading, user, termsAccepted, navigate, refetchTerms]);

  // Show loading spinner while checking auth
  if (isLoading) {
    return (
      <div className="min-h-screen gradient-hero flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }


  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Require terms acceptance for signup
    if (!isLogin && !termsChecked) {
      toast({
        title: "Terms Required",
        description: "Please accept the Terms & Conditions and Privacy Policy to create an account.",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);

    // Save the "keep signed in" preference
    if (keepSignedIn) {
      localStorage.setItem("keepSignedIn", "true");
    } else {
      localStorage.removeItem("keepSignedIn");
      sessionStorage.setItem("tempSession", "true");
    }

    try {
      if (isLogin) {
        const { error } = await supabase.auth.signInWithPassword({
          email,
          password,
        });
        if (error) throw error;
        toast({
          title: "Welcome back!",
          description: "You've successfully logged in.",
        });
      } else {
        const { error } = await supabase.auth.signUp({
          email,
          password,
          options: {
            emailRedirectTo: `${window.location.origin}/analyze`,
          },
        });
        if (error) throw error;
        
        // Update the user_subscriptions table to mark terms as accepted
        const { data: { user: newUser } } = await supabase.auth.getUser();
        if (newUser) {
          await supabase
            .from("user_subscriptions")
            .upsert({
              user_id: newUser.id,
              terms_accepted: true,
              terms_accepted_timestamp: new Date().toISOString(),
            }, { onConflict: 'user_id' });
        }
        
        toast({
          title: "Account created!",
          description: "Welcome to Styloren.",
        });
      }
    } catch (error: any) {
      let message = error.message;
      if (error.message.includes("User already registered")) {
        message = "This email is already registered. Try logging in instead.";
      }
      toast({
        title: "Error",
        description: message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleForgotPassword = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!email) {
      toast({
        title: "Email required",
        description: "Please enter your email address.",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);
    try {
      const response = await supabase.functions.invoke("password-reset", {
        body: { action: "request", email },
      });
      
      if (response.error) throw response.error;
      
      const data = response.data;
      if (data.success) {
        setForgotPasswordStep("otp");
        toast({
          title: "Check your email",
          description: "If this email is registered, you'll receive a 6-digit code shortly.",
        });
      } else {
        toast({
          title: "Error",
          description: data.message || "Failed to send reset code. Please try again.",
          variant: "destructive",
        });
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to send reset code. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleVerifyOtp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!otp || otp.length !== 6) {
      toast({
        title: "Invalid code",
        description: "Please enter the 6-digit code from your email.",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);
    try {
      const response = await supabase.functions.invoke("password-reset", {
        body: { action: "verify", email, otp },
      });
      
      if (response.error) throw response.error;
      
      const data = response.data;
      if (!data.success) {
        toast({
          title: "Invalid code",
          description: data.message || "This code is invalid or has expired. Please try again.",
          variant: "destructive",
        });
        return;
      }
      
      setVerificationToken(data.token);
      setForgotPasswordStep("newPassword");
      toast({
        title: "Code verified",
        description: "Now set your new password.",
      });
    } catch (error: any) {
      toast({
        title: "Verification failed",
        description: error.message || "Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleResetPassword = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Password validation
    if (newPassword.length < 8) {
      toast({
        title: "Password too short",
        description: "Password must be at least 8 characters.",
        variant: "destructive",
      });
      return;
    }
    
    // Check for at least one uppercase, one lowercase, and one number
    const hasUppercase = /[A-Z]/.test(newPassword);
    const hasLowercase = /[a-z]/.test(newPassword);
    const hasNumber = /[0-9]/.test(newPassword);
    
    if (!hasUppercase || !hasLowercase || !hasNumber) {
      toast({
        title: "Password too weak",
        description: "Password must include uppercase, lowercase, and a number.",
        variant: "destructive",
      });
      return;
    }
    
    if (newPassword !== confirmPassword) {
      toast({
        title: "Passwords don't match",
        description: "Please make sure both passwords match.",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);
    try {
      const response = await supabase.functions.invoke("password-reset", {
        body: { action: "reset", email, newPassword },
      });
      
      if (response.error) throw response.error;
      
      const data = response.data;
      if (!data.success) {
        throw new Error(data.message || "Failed to reset password");
      }
      
      // Reset states and go back to login with success message
      setShowForgotPassword(false);
      setForgotPasswordStep("email");
      setOtp("");
      setNewPassword("");
      setConfirmPassword("");
      setVerificationToken(null);
      setIsLogin(true);
      setResetSuccessMessage("Password reset successful! Kindly re-login with your new password.");
      
      // Clear success message after 10 seconds
      setTimeout(() => setResetSuccessMessage(null), 10000);
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message || "Failed to reset password. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const resetForgotPassword = () => {
    setShowForgotPassword(false);
    setForgotPasswordStep("email");
    setOtp("");
    setNewPassword("");
    setConfirmPassword("");
    setVerificationToken(null);
  };


  return (
    <div className="min-h-screen gradient-hero flex flex-col items-center justify-center px-6">
      {/* Decorative elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-32 h-32 rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute bottom-20 right-10 w-40 h-40 rounded-full bg-accent/20 blur-3xl" />
      </div>

      <div className="relative z-10 w-full max-w-md">
        {/* Card */}
        <div className="bg-card/80 backdrop-blur-sm rounded-2xl p-8 shadow-elevated animate-scale-in">
          {/* Logo */}
          <div className="flex items-center justify-center gap-3 mb-8">
            <div className="w-10 h-10 rounded-full gradient-primary flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="font-display text-2xl font-semibold text-foreground">Styloren</span>
          </div>

          {showForgotPassword ? (
            // Forgot Password Flow
            <>
              <button
                onClick={resetForgotPassword}
                className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-6 font-body text-sm"
              >
                <ArrowLeft className="w-4 h-4" />
                Back to sign in
              </button>

              <h1 className="font-display text-2xl font-semibold text-center text-foreground mb-2">
                {forgotPasswordStep === "email" && "Reset password"}
                {forgotPasswordStep === "otp" && "Enter code"}
                {forgotPasswordStep === "newPassword" && "New password"}
              </h1>
              <p className="text-muted-foreground text-center mb-8 font-body text-sm">
                {forgotPasswordStep === "email" && "We'll send you a 6-digit code to reset your password"}
                {forgotPasswordStep === "otp" && "Enter the code we sent to your email"}
                {forgotPasswordStep === "newPassword" && "Choose a strong new password"}
              </p>

              {forgotPasswordStep === "email" && (
                <form onSubmit={handleForgotPassword} className="space-y-6">
                  <div className="space-y-2">
                    <Label htmlFor="reset-email" className="font-body font-medium">Email</Label>
                    <Input
                      id="reset-email"
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      placeholder="your@email.com"
                      required
                      className="h-12 bg-background/50 border-border/50 focus:border-primary font-body"
                    />
                  </div>
                  <Button
                    type="submit"
                    disabled={loading}
                    className="w-full h-12 gradient-primary border-0 font-body font-semibold"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Sending code...
                      </>
                    ) : (
                      "Send reset code"
                    )}
                  </Button>
                </form>
              )}

              {forgotPasswordStep === "otp" && (
                <form onSubmit={handleVerifyOtp} className="space-y-6">
                  <div className="space-y-2">
                    <Label htmlFor="otp" className="font-body font-medium">6-digit code</Label>
                    <Input
                      id="otp"
                      type="text"
                      value={otp}
                      onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))}
                      placeholder="000000"
                      required
                      maxLength={6}
                      className="h-12 bg-background/50 border-border/50 focus:border-primary font-body text-center text-xl tracking-widest"
                    />
                  </div>
                  <Button
                    type="submit"
                    disabled={loading || otp.length !== 6}
                    className="w-full h-12 gradient-primary border-0 font-body font-semibold"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Verifying...
                      </>
                    ) : (
                      "Verify code"
                    )}
                  </Button>
                  <button
                    type="button"
                    onClick={() => setForgotPasswordStep("email")}
                    className="w-full text-sm text-muted-foreground hover:text-foreground font-body transition-colors"
                  >
                    Didn't receive a code? <span className="text-primary">Try again</span>
                  </button>
                </form>
              )}

              {forgotPasswordStep === "newPassword" && (
                <form onSubmit={handleResetPassword} className="space-y-6">
                  <div className="space-y-2">
                    <Label htmlFor="new-password" className="font-body font-medium">New password</Label>
                    <div className="relative">
                      <Input
                        id="new-password"
                        type={showNewPassword ? "text" : "password"}
                        value={newPassword}
                        onChange={(e) => setNewPassword(e.target.value)}
                        placeholder="••••••••"
                        required
                        minLength={8}
                        className="h-12 bg-background/50 border-border/50 focus:border-primary font-body pr-12"
                      />
                      <button
                        type="button"
                        onClick={() => setShowNewPassword(!showNewPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                      >
                        {showNewPassword ? <Eye className="w-5 h-5" /> : <EyeOff className="w-5 h-5" />}
                      </button>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Min 8 characters with uppercase, lowercase, and number
                    </p>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="confirm-password" className="font-body font-medium">Confirm password</Label>
                    <div className="relative">
                      <Input
                        id="confirm-password"
                        type={showConfirmPassword ? "text" : "password"}
                        value={confirmPassword}
                        onChange={(e) => setConfirmPassword(e.target.value)}
                        placeholder="••••••••"
                        required
                        minLength={8}
                        className="h-12 bg-background/50 border-border/50 focus:border-primary font-body pr-12"
                      />
                      <button
                        type="button"
                        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                      >
                        {showConfirmPassword ? <Eye className="w-5 h-5" /> : <EyeOff className="w-5 h-5" />}
                      </button>
                    </div>
                  </div>
                  <Button
                    type="submit"
                    disabled={loading}
                    className="w-full h-12 gradient-primary border-0 font-body font-semibold"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Updating password...
                      </>
                    ) : (
                      "Update password"
                    )}
                  </Button>
                </form>
              )}
            </>
          ) : (
            // Login/Signup Flow
            <>
              {/* Success message after password reset */}
              {resetSuccessMessage && (
                <Alert className="mb-6 bg-green-500/10 border-green-500/30 text-green-600 dark:text-green-400">
                  <AlertDescription className="font-body text-sm">
                    {resetSuccessMessage}
                  </AlertDescription>
                </Alert>
              )}
              
              <h1 className="font-display text-3xl font-semibold text-center text-foreground mb-2">
                {isLogin ? "Welcome back" : "Create account"}
              </h1>
              <p className="text-muted-foreground text-center mb-8 font-body">
                {isLogin ? "Sign in to continue your style journey" : "Start your style journey today"}
              </p>

              <form onSubmit={handleAuth} className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="email" className="font-body font-medium">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="your@email.com"
                    required
                    className="h-12 bg-background/50 border-border/50 focus:border-primary font-body"
                  />
                </div>

                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="password" className="font-body font-medium">Password</Label>
                    {isLogin && (
                      <button
                        type="button"
                        onClick={() => setShowForgotPassword(true)}
                        className="text-sm text-primary hover:text-primary/80 font-body transition-colors"
                      >
                        Forgot password?
                      </button>
                    )}
                  </div>
                  <Input
                    id="password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="••••••••"
                    required
                    minLength={6}
                    className="h-12 bg-background/50 border-border/50 focus:border-primary font-body"
                  />
                </div>

                {/* Keep me signed in checkbox */}
                <div className="flex items-center gap-3">
                  <button
                    type="button"
                    onClick={() => setKeepSignedIn(!keepSignedIn)}
                    className={`w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 transition-colors ${
                      keepSignedIn 
                        ? "bg-primary border-primary" 
                        : "border-border hover:border-primary/50"
                    }`}
                  >
                    {keepSignedIn && (
                      <svg className="w-3 h-3 text-primary-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    )}
                  </button>
                  <p className="text-sm text-muted-foreground font-body">
                    Keep me signed in
                  </p>
                </div>

                {/* Terms checkbox - only show for signup */}
                {!isLogin && (
                  <div className="flex items-start gap-3">
                    <button
                      type="button"
                      onClick={() => setTermsChecked(!termsChecked)}
                      className={`w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 mt-0.5 transition-colors ${
                        termsChecked 
                          ? "bg-primary border-primary" 
                          : "border-border hover:border-primary/50"
                      }`}
                    >
                      {termsChecked && (
                        <svg className="w-3 h-3 text-primary-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                        </svg>
                      )}
                    </button>
                    <p className="text-sm text-muted-foreground font-body leading-relaxed">
                      I agree to the{" "}
                      <button
                        type="button"
                        onClick={() => setShowTermsDialog(true)}
                        className="text-primary underline hover:text-primary/80"
                      >
                        Terms & Conditions
                      </button>{" "}
                      and{" "}
                      <button
                        type="button"
                        onClick={() => setShowPrivacyDialog(true)}
                        className="text-primary underline hover:text-primary/80"
                      >
                        Privacy Policy
                      </button>
                    </p>
                  </div>
                )}

                <Button
                  type="submit"
                  disabled={loading}
                  className="w-full h-12 gradient-primary border-0 font-body font-semibold"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      {isLogin ? "Signing in..." : "Creating account..."}
                    </>
                  ) : (
                    isLogin ? "Sign in" : "Create account"
                  )}
                </Button>
              </form>

              {/* Toggle */}
              <div className="mt-6 text-center">
                <button
                  onClick={() => {
                    setIsLogin(!isLogin);
                    setTermsChecked(false);
                  }}
                  className="text-sm text-muted-foreground hover:text-foreground font-body transition-colors"
                >
                  {isLogin ? "Don't have an account? " : "Already have an account? "}
                  <span className="text-primary font-medium">
                    {isLogin ? "Sign up" : "Sign in"}
                  </span>
                </button>
              </div>
            </>
          )}
        </div>
      </div>

      {/* Terms Dialog */}
      <Dialog open={showTermsDialog} onOpenChange={setShowTermsDialog}>
        <DialogContent className="max-w-lg max-h-[80vh] p-0">
          <DialogHeader className="p-6 pb-0">
            <div className="flex items-center">
              <DialogTitle className="font-display text-lg">Terms & Conditions</DialogTitle>
            </div>
          </DialogHeader>
          <ScrollArea className="max-h-[60vh] px-6 pb-6">
            <TermsContent />
          </ScrollArea>
        </DialogContent>
      </Dialog>

      {/* Privacy Dialog */}
      <Dialog open={showPrivacyDialog} onOpenChange={setShowPrivacyDialog}>
        <DialogContent className="max-w-lg max-h-[80vh] p-0">
          <DialogHeader className="p-6 pb-0">
            <div className="flex items-center">
              <DialogTitle className="font-display text-lg">Privacy Policy</DialogTitle>
            </div>
          </DialogHeader>
          <ScrollArea className="max-h-[60vh] px-6 pb-6">
            <PrivacyContent />
          </ScrollArea>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Auth;
