import { useNavigate } from "react-router-dom";
import { ArrowLeft, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";

const TermsConditions = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen gradient-warm">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-sm border-b border-border/50">
        <div className="container mx-auto px-6 py-4 flex items-center gap-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate("/account")}
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div className="w-8 h-8 rounded-full gradient-primary flex items-center justify-center">
            <FileText className="w-4 h-4 text-primary-foreground" />
          </div>
          <span className="font-display text-xl font-semibold text-foreground">Terms & Conditions</span>
        </div>
      </header>

      {/* Content */}
      <main className="container mx-auto px-6 py-8 max-w-2xl">
        <div className="bg-card/80 backdrop-blur-sm rounded-2xl p-6 border border-border/50">
          <div className="prose prose-sm max-w-none text-foreground">
            <h1 className="font-display text-2xl font-bold text-foreground mb-2">Terms & Conditions – Styloren</h1>
            <p className="text-muted-foreground mb-6">Last updated: December 18, 2025</p>
            
            <p className="text-foreground mb-6">
              Welcome to Styloren. By accessing or using the Styloren mobile application ("App"), you agree to comply with and be bound by these Terms & Conditions ("Terms"). If you do not agree, please do not use the App.
            </p>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">1. Use of the App</h2>
            <p className="text-foreground mb-3">
              Styloren provides AI-powered outfit analysis and styling recommendations for informational and personal use only.
            </p>
            <p className="text-foreground mb-2">You agree to:</p>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-4">
              <li>Use the App lawfully and responsibly</li>
              <li>Not misuse, reverse engineer, or attempt to disrupt the App or its services</li>
              <li>Not upload unlawful, harmful, or offensive content</li>
            </ul>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">2. AI-Generated Recommendations</h2>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-4">
              <li>Styling suggestions are generated by artificial intelligence.</li>
              <li>Recommendations are advisory only and subjective in nature.</li>
              <li>Styloren does not guarantee fashion outcomes, personal satisfaction, or results.</li>
            </ul>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">3. User Content & Scan History</h2>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-4">
              <li>When you upload outfit photos, Styloren processes them to generate styling recommendations.</li>
              <li>By default, your scans and analysis may be saved to your Scan History for your convenience.</li>
              <li>You may disable scan history storage at any time via Account → My Activity → Scan History.</li>
              <li>You retain ownership of your content. Styloren does not claim ownership over your photos.</li>
            </ul>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">4. Accounts & Security</h2>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-4">
              <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
              <li>You agree to notify us immediately of any unauthorized access to your account.</li>
              <li>Styloren is not responsible for losses caused by unauthorized access due to user negligence.</li>
            </ul>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">5. Subscriptions & Payments</h2>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-4">
              <li>Styloren may offer paid plans and features.</li>
              <li>Prices, features, and availability may change at any time.</li>
              <li>All payments are handled via third-party payment platforms and are subject to their terms.</li>
              <li>Refunds, if applicable, follow platform-specific policies.</li>
            </ul>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">6. Intellectual Property</h2>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-4">
              <li>All app content, branding, design, and software are the property of Styloren.</li>
              <li>You may not copy, reproduce, or redistribute any part of the App without permission.</li>
            </ul>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">7. Limitation of Liability</h2>
            <p className="text-foreground mb-2">Styloren shall not be liable for:</p>
            <ul className="list-disc pl-6 space-y-1 text-foreground mb-3">
              <li>Any indirect or consequential damages</li>
              <li>Loss of data, satisfaction, or personal decisions made based on AI suggestions</li>
              <li>Service interruptions or technical issues beyond reasonable control</li>
            </ul>
            <p className="text-foreground mb-4">Use of the App is at your own discretion and risk.</p>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">8. Termination</h2>
            <p className="text-foreground mb-4">
              Styloren reserves the right to suspend or terminate access to the App if these Terms are violated.
            </p>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">9. Changes to These Terms</h2>
            <p className="text-foreground mb-4">
              We may update these Terms from time to time. Continued use of the App after changes means you accept the updated Terms.
            </p>

            <hr className="border-border/50 my-6" />

            <h2 className="font-display text-lg font-semibold text-foreground mt-6 mb-3">10. Contact Us</h2>
            <p className="text-foreground mb-2">
              For questions or concerns regarding these Terms, contact:
            </p>
            <p className="text-foreground">
              📧 <a href="mailto:help@styloren.com" className="text-primary underline">help@styloren.com</a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default TermsConditions;
